## Assignment 2 - Data Analysis - Web Mining

The web is an immense source of data, offering valuable insights across various domains. In this assignment, we will explore different ways to process, and analyze web data to uncover meaningful patterns and make informed decisions. Through five practical exercises, we will apply key data mining techniques to real-world scenarios.

Each exercise focuses on a specific application:

* *Exercise 1* - Clickbait classification
* *Exercise 2* - Sentiment analysis on comments
* *Exercise 3* - Movie recommendation
* *Exercise 4* - Association rules in online shopping
* *Exercise 5* - Clustering of mobile apps

These exercises will provide hands-on experience in working with real-world data collected from the web, helping you understand its potential for analysis.

For this assignment, complete all exercises that are marked in <span style='color:red;font-weight:bold'>red</span>. Please make sure all your cells run correctly (try to *Clear All Outputs* then *Run All* once before submitting). **Check the cells outputs are visibles even for the coding parts**

The assignment is due for <span style='color:red;font-weight:bold'>Thursday 26th of March 2026 at 23:59</span>.

No report is needed as all questions can be answered directly in this notebook file. You only need to give this notebook file completed on the [Moodle assignment page](https://moodle.msengineering.ch/mod/assign/view.php?id=229885). Only one file per group is required for submission.

If you have any questions or issues, please contact one of the assistants below:
- Cédric Campos Carvalho (*Teams* might be easier to discuss, mail: cedric.camposcarvalho@heig-vd.ch)
- Elena Najdenovska (mail: elena.najdenovska@heig-vd.ch)


Teacher : 
- Laura Elena Raileanu <Laura.Raileanu@heig-vd.ch>(mail: Laura.Raileanu@heig-vd.ch)

### Exercise 1 - Clickbait classification

The objective of this first part is to model a filter for "clickbait" in online news media. Clickbait headlines are designed to attract attention and drive clicks, often at the expense of accuracy or relevance.

To achieve this, we provide you with a dataset containing more than 10'000 press headlines collected in 2016. Each row in this dataset corresponds to a single headline, which is described by the following two attributes:

* `headline`: the text representing the title
* `clickbait`: the label identifying whether the title is a clickbait *(1)* or not *(0)*.

In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import FunctionTransformer

import warnings
warnings.simplefilter("ignore")

In [2]:
df_1 = pd.read_excel('data/part1_classification/news_clickbait.xlsx', engine="openpyxl")
df_1

                                                headline  clickbait
0      You Need To Tell Us If These Things Are Doughnuts          1
1      15 Great Pieces Of Relationship Advice From Books          1
2        Improved E-Mail Service From a Dedicated Device          0
3      Two MBTA Green Line trains collide in Newton, ...          0
4           17 Struggles All Smartypants Will Understand          1
...                                                  ...        ...
10536           Can You Match The Phone To The R&B Video          1
10537  19 Soul Food Recipes That Are Almost As Good A...          1
10538  16 Photos Of Desis That Will Give You Intense ...          1
10539  City Plans to Make Older Buildings Refit to Sa...          0
10540                         Iraqis accept constitution          0

[10541 rows x 2 columns]

<p style='color:red;font-weight:bold'>Exercise 1.1 :</p>

The first step is to separate the dataset into two sets (training and test), complete the input parameters of `train_test_split` function.

In [3]:
... = train_test_split(...)

SyntaxError: cannot assign to ellipsis here. Maybe you meant '==' instead of '='? (4127458987.py, line 1)

<p style='color:red;font-weight:bold'>Exercise 1.2 :</p>

Create a pre-processing `Pipeline` using [scikit-learn Pipeline object](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html).
In your pipeline you need:
- Vectorize your headlines with Term frequency-inverse document frequency.
- Transform your data in case of [`sparse matrix`](https://docs.scipy.org/doc/scipy/reference/sparse.html#module-scipy.sparse), so the data goes through the model without any issues.

**Do not forget to remove words giving no information for classification (i.e. [stop words](https://en.wikipedia.org/wiki/Stop_word)).**

In [ ]:
preprocessor = Pipeline(...)

<p style='color:red;font-weight:bold'>Exercise 1.3 :</p>

Create the pipeline using `make_pipeline`, combining the pre-processing pipeline and the `GaussianNB` model. Then, train the pipeline and find the score obtained with the test set.

In [ ]:
# TODO 1.3

<p style='color:red;font-weight:bold'>Exercise 1.4 :</p>

Modify your split ratio for the training/testing set and see if there's a difference in the model's performances. Please explain your findings.

*TODO 1.4*

<p style='color:red;font-weight:bold'>Exercise 1.5 :</p>

Keep your split validation but now incorporate [cross validation](https://en.wikipedia.org/wiki/Cross-validation_(statistics)). Use the [`cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) function and a K-Folding with 5 splits over the training set without using the test set. Then, calculate the averaged accuracy (with standard deviation) for 5 folds.

**Explain the results obtained and how to read them compared to the split validation.**

In [ ]:
# TODO 1.5

*TODO 1.5*

<p style='color:red;font-weight:bold'>Exercise 1.6 :</p>

Try to use atleast 3 different classifiers and report their results in a table. Compare the results between them.

In [ ]:
# TODO 1.6

*TODO 1.6*

<p style='color:red;font-weight:bold'>Exercise 1.7 :</p>

In text processing we often use a stemming step for the pre-processing, explain what it consists and how it can be useful then give an example.

*TODO 1.7*

### Exercise 2 - Sentiment analysis on comments

The goal of the second part is to analyze tweets from the COVID-19 period and perform sentiment analysis to determine whether they express a positive or negative sentiment.

In the first step, we will work with the dataset `CoronaTwitterComments_2labels.xlsx`, which contains approximately 3'000 comments related to COVID-19 from Twitter in March 2020. These comments are already labeled with *1* (positive comment) or *-1* (negative comment). In the second step, we will consider the dataset `CoronaTwitterComments_3labels.xlsx`, which includes additional neutral comments (labeled with *0*). You will see how we can process the text data with the help of [WordNet](https://wordnet.princeton.edu/) to retrieve a sentiment and evaluate the results.

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd

import nltk

In [ ]:
# NLTK packages needed for this exercise, feel free to add some if you need it.

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('sentiwordnet')

In [ ]:
corona_tweets2 = pd.read_excel('data/part2_sentimentanalysis/CoronaTwitterComments_2labels.xlsx', engine="openpyxl")
corona_tweets3 = pd.read_excel('data/part2_sentimentanalysis/CoronaTwitterComments_3labels.xlsx', engine="openpyxl")

print(corona_tweets2.SentimentLabel.unique(), corona_tweets3.SentimentLabel.unique())
corona_tweets2

<p style='color:red;font-weight:bold'>Exercise 2.1 :</p>

The first step is to pre-process the text (like in previous exercise) to later use a WordNet sentiment analysis over it.

The class inherits from `BaseEstimator` and `TransformerMixin`, ensuring seamless integration with other scikit-learn modules. This allows it to utilize the familiar `fit`, `transform`, and `fit_transform` functions of the library.

Your task is to update the `NLTKPreprocessor` class with the needed functions to be used later in the `transform` function.
- Add a tokenizer specialized in tweets.
- Remove stop words and other unuseful characters.
- Transform in lowercase the text
- Lemmatize the text using for Wordnet.

*Advice : If you encounter any issues, refer to the `apply_pipeline` function to understand how it works. This function should **not** be modified.*

In [ ]:
class NLTKPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        # TODO        

        self.pipeline = [
            # TODO
        ]
    def apply_pipeline(self, x):
        for transform in self.pipeline:
            x = transform(x)
        return x


    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return [self.apply_pipeline(x) for x in X]

<p style='color:red;font-weight:bold'>Exercise 2.2 :</p>

The next step is to create the `WordNetSentimentAnalyzer`. You will need to create three functions to add to your pipeline : 
1. The WordNet sentiment analysis requires to have the tag of each word of the sentence. Tagging in part of speech (POS) is the process of assigning grammatical categories, such as nouns, verbs, or adjectives, to words in a text based on their role in a sentence. `nltk` has a pre-trained model that can tag these words, find it and apply it to the pipeline.
2. For WordNet the tagging is different from the pre-trained `nltk` model. Create a function replacing the tags with the WordNet tags using `nltk.corpus.wordnet` module.
3. Create the sentiment function which sums the positive sentiment ($\text{pos}$) and negative sentiment ($\text{neg}$) of each word (using `nltk.corupus.sentiwordnet` module). The value needs to be taken in account only if it is superior to a certain threshold (i.e. $\text{treshold} = 0.05$). Then, return a single value representing the sentiment of the sentence such as it is $\text{sentiment} < 0$ if it's negative and $\text{sentiment} > 0$ if positive.

In [ ]:
class WordNetSentimentAnalyzer(BaseEstimator, TransformerMixin):
    def __init__(self):
        # TODO

        self.pipeline = [
            # TODO
        ]

    def apply_pipeline(self, x):
        for transform in self.pipeline:
            x = transform(x)
        return x
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        return [self.apply_pipeline(x) for x in X]

<p style='color:red;font-weight:bold'>Exercise 2.3 :</p>

Create two functions that return the sentiment class to compare it to the labels.
* `get_sentiment_class_2` : For positive and negative only.
* `get_sentiment_class_3` : For positive, negative and neutral.

**Do not forget that it is going to be used in a `scikit-learn` `Pipeline`!**

In [ ]:
def get_sentiment_class_2(sent_val):
    return # TODO

def get_sentiment_class_3(sent_val):
    return # TODO

<p style='color:red;font-weight:bold'>Exercise 2.4 :</p>

Create a `scikit-learn` `Pipeline` using the 3 previous *Transformers* that you created (using the 2 class sentiment).

Then, complete the function `get_sentiment_tweet` and test it with your own Tweet (**Do not change its signature !**).

In [ ]:
pipeline = Pipeline(steps=[
    # TODO
])

def get_sentiment_tweet(tweet:str)-> int:
    return # TODO

# TODO

<p style='color:red;font-weight:bold'>Exercise 2.5 :</p>

Compute the accuracy obtained with all tweets of the dataset. Then, do the same for the 3 labels class.

In [ ]:
# TODO 2.5

<p style='color:red;font-weight:bold'>Exercise 2.6 :</p>

Analyze the results of each pre-processing (`NLTKPreprocessor`) step to try to understand what you could do to improve it. For example, what could you add into this pipeline ? *(No implementation needed)*

### Exercise 3 - Movie recommendation

The objective of this exercise is to create a recommendation system of movies based on the user ratings. We will focus on the collaborative approach for movie recommendation using the provided dataset, which contains approximately 9'800 movies rated by 610 users from MovieLens.

More specifically, the `movies.csv` dataset, which describes the movies, includes three attributes:

* `movieId`: unique identifier of the movie
* `title`: the title of the movie (with the release year in parentheses)
* `genres`: the genres of the movie

The `ratings.csv` dataset, which contains user ratings for the movies, includes four attributes:

* `userId`: unique identifier of the user
* `movieId`: unique identifier of the movie
* `rating`: the user's rating for the corresponding movie
* `timestamp`: the timestamp of the rating

In [ ]:
from sklearn.neighbors import NearestNeighbors
import pandas as pd

In [ ]:
df_movies = pd.read_csv('data/part3_recommandationdesfilms/movies.csv')
df_ratings = pd.read_csv('data/part3_recommandationdesfilms/ratings.csv')

df_3 = pd.merge(df_movies, df_ratings, on='movieId')
df_3

<p style='color:red;font-weight:bold'>Exercise 3.1 :</p>

Use `df_3` to create a second `DataFrame` with the rating of every movies for each `userId`. If the user never watched a movie the value is $0$. 
For this step, use the [`pivot` function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html).

In [ ]:
user_item_matrix = ... # TODO 3.1
X = user_item_matrix.to_numpy()
X

<p style='color:red;font-weight:bold'>Exercise 3.2 :</p>

First separate the data using `train_test_split` function with $20\%$ of the data in the test set.
Create an `knn` model using the [`NearestNeighbors`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestNeighbors.html#sklearn.neighbors.NearestNeighbors) model from `scikit-learn`. For now use $N=80$, and the `cosine` metric, then train it.

**Explain in few sentences how does the `cosine` metric works by taking our case in an example (include the formula).**

In [ ]:
... = train_test_split(...)

knn = ...

...

*TODO 3.2*

<p style='color:red;font-weight:bold'>Exercise 3.3 :</p>

Create the `predict` function by using the previous trained model.

*Hints : Think about the model returns and what they represent. Then, use the closest indexes to obtain information on the best matching movies.*

In [ ]:
def predict(X, user_item_matrix, knn):
    ...
    return ...

<p style='color:red;font-weight:bold'>Exercise 3.4 :</p>

Finally, complete the `prec_at_k` function, which measures the precision of our model. This metric calculates how many of the top $k$ movies recommended to a user are actually relevant. A movie is considered relevant if the user has given it a score of at least 4..

In [ ]:
def prec_at_k(Y_pred, user_item_matrix, k):
    ...
    return ...

<p style='color:red;font-weight:bold'>Exercise 3.5 :</p>

Now, use the function with three different values for k ($5$, $15$, $25$) each time. Then, use different $N$ neighbours and a different split ratio.

Report all your results bellow and explain the impact of these hyperparameters in the model.

In [ ]:
# TODO 3.5

*TODO 3.5*

### Exercise 4 - Association rules in online shopping

In this fourth part, we will focus on a **Market Basket Analysis** problem. The dataset provided contains **online sales transactions** from an e-commerce site over one year. Our goal is to generate **association rules** based on these sales to identify which items are frequently bought together. You can refer to the source mentioned in the **README file** included with the data for more details.  

The dataset is structured as follows, with each row representing the details of a product sale:  
- `InvoiceNo`: invoice/sale identifier  
- `StockCode`: product identifier  
- `Description`: purchased product  
- `Quantity`: quantity sold  
- `InvoiceDate`: order/payment date  
- `UnitPrice`: price of the product  
- `CustomerID`: customer identifier  
- `Country`: customer’s country of residence

In [4]:
from sklearn.preprocessing import MultiLabelBinarizer
import pandas as pd
import openpyxl

In [5]:
df_4 = pd.read_excel('data/part4_marketbasketanalysis/OnlineRetailDataset.xlsx', engine='openpyxl')
df_4

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
397919,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
397920,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
397921,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
397922,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
397923,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

<p style='color:red;font-weight:bold'>Exercise 4.1 :</p>

Transform the given dataset into a one-hot encoded format for association rule mining. Group items by customer so that each row represents a unique customer with a list of purchased items. Then, convert this into a binary matrix where each column is an item, and values indicate whether a customer bought that item (1) or not (0). Use [`MultiLabelBinarizer`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html) to achieve this.

In [6]:
df_4_clean = df_4.dropna(subset=['CustomerID','Description']).copy()

customer_items = (
    df_4_clean.groupby('CustomerID')['Description']
    .apply(list)
    .reset_index()
)
print(customer_items.head())

#one-hot encoding
mlb = MultiLabelBinarizer()
one_hot = pd.DataFrame(
    mlb.fit_transform(customer_items['Description']),
    columns=mlb.classes_,
    index=customer_items['CustomerID']
)

one_hot = one_hot.reset_index()
print(one_hot.head())
print(one_hot.shape)

   CustomerID                                        Description
0       12346                   [MEDIUM CERAMIC TOP STORAGE JAR]
1       12347  [BLACK CANDELABRA T-LIGHT HOLDER, AIRLINE BAG ...
2       12348  [72 SWEETHEART FAIRY CAKE CASES, 60 CAKE CASES...
3       12349  [PARISIENNE CURIO CABINET, SWEETHEART WALL TID...
4       12350  [CHOCOLATE THIS WAY METAL SIGN, METAL SIGN NEI...
   CustomerID   4 PURPLE FLOCK DINNER CANDLES   50'S CHRISTMAS GIFT BAG LARGE  \
0       12346                               0                               0
1       12347                               0                               0
2       12348                               0                               0
3       12349                               0                               0
4       12350                               0                               0

    DOLLY GIRL BEAKER   I LOVE LONDON MINI BACKPACK  \
0                   0                             0
1                   0                             0
2                   0                             0
3                   0                             0
4                   0                             0

    I LOVE LONDON MINI RUCKSACK   NINE DRAWER OFFICE TIDY  \
0                             0                         0
1                             0                         0
2                             0                         0
3                             0                         0
4                             0                         0

    OVAL WALL MIRROR DIAMANTE    RED SPOT GIFT BAG LARGE  \
0                            0                         0
1                            0                         0
2                            0                         0
3                            0                         0
4                            0                         0

    SET 2 TEA TOWELS I LOVE LONDON   ...  ZINC STAR T-LIGHT HOLDER   \
0                                 0  ...                          0
1                                 0  ...                          0
2                                 0  ...                          0
3                                 0  ...                          0
4                                 0  ...                          0

   ZINC SWEETHEART SOAP DISH  ZINC SWEETHEART WIRE LETTER RACK  \
0                          0                                 0
1                          0                                 0
2                          0                                 0
3                          0                                 0
4                          0                                 0

   ZINC T-LIGHT HOLDER STAR LARGE  ZINC T-LIGHT HOLDER STARS LARGE  \
0                               0                                0
1                               0                                0
2                               0                                0
3                               0                                0
4                               0                                0

   ZINC T-LIGHT HOLDER STARS SMALL  ZINC TOP  2 DOOR WOODEN SHELF   \
0                                0                               0
1                                0                               0
2                                0                               0
3                                0                               0
4                                0                               0

   ZINC WILLIE WINKIE  CANDLE STICK  ZINC WIRE KITCHEN ORGANISER  \
0                                 0                            0
1                                 0                            0
2                                 0                            0
3                                 0                            0
4                                 0                            0

   ZINC WIRE SWEETHEART LETTER TRAY
0                                 0
1                                 0
2                                 0
3                                 0
4                                 0

[5 rows x 3878 columns]
(4339, 3878)

<p style='color:red;font-weight:bold'>Exercise 4.2 :</p>

Finally, create the association rules based on the frequent patterns obtained through `FP-growth` algorithm. Check [`mlxtend`](https://rasbt.github.io/mlxtend/) documentation to complete this task. Then, show what are the association rules with a minimum of $0.9$ confidence.

In [12]:
from mlxtend.frequent_patterns import fpgrowth, association_rules

basket = one_hot.set_index('CustomerID').astype(bool) #I had a warning explaining that mlxtend prefers True/False than 0/1 -> astype(bool)
#found frequent items
frequent_itemsets = fpgrowth(
    basket,
    min_support=0.05,
    verbose=False
)

print(frequent_itemsets.head())

#gen association rules
rules = (association_rules
     (
        frequent_itemsets,
        metric="confidence",
        min_threshold=0.9
    ))
print(rules.shape)
print(rules.head())

    support           itemsets
0  0.203042  frozenset({2767})
1  0.103711  frozenset({2656})
2  0.097488  frozenset({2865})
3  0.095414   frozenset({109})
4  0.089422   frozenset({147})
(5, 14)
                     antecedents        consequents  antecedent support  \
0              frozenset({2527})  frozenset({1509})            0.073519
1        frozenset({2865, 2527})  frozenset({1509})            0.062687
2        frozenset({2767, 2527})  frozenset({1509})            0.059691
3  frozenset({2865, 2767, 2527})  frozenset({1509})            0.053699
4  frozenset({2767, 1509, 2527})  frozenset({2865})            0.056465

   consequent support   support  confidence       lift  representativity  \
0            0.089191  0.068218    0.927900  10.403506               1.0
1            0.089191  0.060152    0.959559  10.758464               1.0
2            0.089191  0.056465    0.945946  10.605838               1.0
3            0.089191  0.051625    0.961373  10.778809               1.0
4            0.097488  0.051625    0.914286   9.378453               1.0

   leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
0  0.061661   12.632524       0.975604  0.721951   0.920839    0.846379
1  0.054561   22.521821       0.967713  0.655779   0.955599    0.816989
2  0.051141   16.849965       0.963207  0.610973   0.940653    0.789510
3  0.046835   23.579832       0.958707  0.565657   0.957591    0.770092
4  0.046120   10.529308       0.946835  0.504505   0.905027    0.721918

<p style='color:red;font-weight:bold'>Exercise 4.3 :</p>

Do you observe any changes in the different parameters of the *FP-Growth* and *Association Rules* functions ? Please comment on the chosen parameters and the results obtained.

## For the FP-Growth parameters :

We use min_support = 0.05. This means only itemsets appearing in at least 5% of customers are kept.

Compared to a smaller value (for example 0.01), there will be fewer frequent itemsets, reduces computation time, generates more meaningful and general patterns. A lower min_support (for example 0.01), will produce many more frequent itemsets, generates a very large number of rules, increases computation tima and may produce less meaningful rules. Using 0.05 as min_support, we focus on more common purchasing patterns, which improves interpretability.

## For Association Rules parameters :

We use metric="confidence" and min_threshold=0.9. This means only rules with confidence >= 90% are kept. This ensures strong relationships between products and keep only strong and reliable rules. If we used a lower threshold, we should obtain more rules, but some of them might be less meaningful or less reliable. Therefore, chosing a high confidence value helps reduce noise and focuse on the most relevant associations.

<p style='color:red;font-weight:bold'>Exercise 4.4 :</p>

Is it possible to use other column(s) from the initial data to generate interesting rules?

Yes, other column such as Country, InvoiceNo or InvoiceDate can be used to generate more interesting rules. Grouping by invoiceNo allows analyzing products bought in the same transaction, which is more relevant for market basket analysis. Using country allows discovering geographical buying patterns. Using invoicedate enables seasonal analysis, such as identifying products frequently bought during holidays or season.

### Exercise 5 - Clustering of mobile apps

In this final part, we will perform clustering of applications from the Google Play Store. You can refer to the source mentioned in the **README file** included with the data for more details.

Among the attributes available in the `googleplaystore.xlsx` file, we will use the following:

* `Rating`: overall user rating of the application
* `Reviews`: number of user reviews
* `Size`: size of the application
* `Installs`: number of users who installed the application
* `Price`: price of the application

In [ ]:
from sklearn.cluster import KMeans
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
df_5 = pd.read_excel('data/part5_clustering/googleplaystore.xlsx', engine='openpyxl')
df_5

<p style='color:red;font-weight:bold'>Exercise 5.1 :</p>

Select the numerical features of the dataset then standardize them by removing the mean and scaling to unit variance. 
Then, do a first training using [`KMeans`](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) algorithm with $5$ clusters.

In [ ]:
# TODO 5.1

<p style='color:red;font-weight:bold'>Exercise 5.2 :</p>

Complete the function `average_cluster_distance` to compute a clustering performance metric. It should return a list where the first value is the global average distance from all samples to their assigned centroids, followed by the average distances per centroid.

In [ ]:
def average_cluster_distance(X, model):
    ...
    return ...

avg_distances = average_cluster_distance(...)
print(avg_distances)

<p style='color:red;font-weight:bold'>Exercise 5.3 :</p>

Try using different values for the maximum number of iterations of the *K-Means Algorithm*. Then, report your results and describe them.

In [ ]:
# TODO 5.3

*TODO 5.3*

<p style='color:red;font-weight:bold'>Exercise 5.4 :</p>

Analyze how the category distributions change when clustering with $\text{n\_cluster} = {2,3,4,5}$ and compare the results. Observe how categories are grouped within each cluster and note any significant shifts as the number of clusters increases. Describe the distributions obtained and evaluate the average distances for each $\text{n\_cluster}$.

In [ ]:
# TODO 5.4

*TODO 5.4*